mongos> var arr=db.getCollectionNames();for(var _coll in arr){ var aaa=db.getCollection(arr[_coll]).findOne();print('|--------------collection:'+arr[_coll]);for (var key in aaa) { print (key) ; }}


|--------------collection:UserInfo
_id
className
userType
uid
userName
mobile
lastLoginTime
createTime
province
city
mac
batchNo
nickName
|--------------collection:UserSmsInfo
_id
className
taskId
mobile
content
sign
sendTime
submitStatus
submitMsg
createUserId
createTime
modifyUserId
modifyTime
remark
channelId
hospitalId
gwId
customizeId
smsType
request
response
receiveStatus
receiveTime
|--------------collection:UserSmsReportInfo
_id
className
taskId
mobile
receiveStatus
receiveTime
|--------------collection:WiFiAcFlowVo
_id
className
gwid
in
out
|--------------collection:adClickv1
_id
uid
adid
guuid
createTime
|--------------collection:adLoadv1
_id
uid
adid
guuid
guuidCTime
createTime
ip
ua
url
|--------------collection:adPlayv1
_id
uid
adid
guuid
createTime
|--------------collection:bblink_wifilog_userauthorize_count
_id
gwid
user_type
count
hos_id
sup_id
day
hour
create_time
|--------------collection:bblink_wifilog_userauthorize_uv_day
_id
day
uv
create_time
|--------------collection:bblink_wifilog_userauthorize_uv_day_type
_id
day
user_type
uv
create_time
|--------------collection:bblink_wifilog_userauthorize_uv_hos_day
_id
hos_id
day
uv
sup_id
create_time
|--------------collection:bblink_wifilog_userauthorize_uv_hos_day_type
_id
hos_id
day
user_type
uv
sup_id
create_time
|--------------collection:bblink_wifilog_userconnect_count
|--------------collection:bblink_wifilog_userconnect_uv_day
|--------------collection:bblink_wifilog_userconnect_uv_hos_day
|--------------collection:bblink_wifilog_userdetect_uv_day
|--------------collection:bblink_wifilog_userdetect_uv_hos_day
|--------------collection:bblink_wifilog_userlogin_count
_id
gwid
user_type
count
hos_id
sup_id
day
hour
create_time
|--------------collection:bblink_wifilog_userlogin_uh_day
_id
day
uh
create_time
|--------------collection:bblink_wifilog_userlogin_uh_day_type
_id
day
user_type
uh
create_time
|--------------collection:bblink_wifilog_userlogin_uv_day
_id
day
uv
create_time
|--------------collection:bblink_wifilog_userlogin_uv_day_type
_id
day
user_type
uv
create_time
|--------------collection:bblink_wifilog_userlogin_uv_hos_day
_id
hos_id
day
uv
sup_id
create_time
|--------------collection:bblink_wifilog_userlogin_uv_hos_day_type
_id
hos_id
day
user_type
uv
sup_id
create_time
|--------------collection:gurlinfo
_id
guid
curl
time
|--------------collection:sitePVv3
_id
pid
guuid
guuidCTime
uuid
uuidCTime
ip
ua
createTime
pageTitle
url
referer
language
cookieEnabled
sw
sh
prevPID
prevTime
|--------------collection:system.indexes
v
key
name
ns
|--------------collection:test
_id
name
age
|--------------collection:userAuthorizedLog
_id
className
userId
gwId
userType
userMac
authorizeTime
createTime
