set nocompatible              " be iMproved, required
filetype off                  " required

" config leader key
let mapleader = ","

" neocomplcache let config 
let g:neocomplcache_enable_at_startup = 1
" neocomplcache tab key setting
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

" move commands
"Crtl+ww cycle though all windows
"Crtl+wh takes you left a window
"Crtl+wj takes you down a window
"Crtl+wk takes you up a window
"Crtl+wl takes you right a window

" easymotion config
" ref http://www.wklken.me/posts/2015/06/07/vim-plugin-easymotion.html
let g:EasyMotion_smartcase = 1
"let g:EasyMotion_startofline = 0 " keep cursor colum when JK motion
map <Leader><leader>h <Plug>(easymotion-linebackward)
map <Leader><Leader>j <Plug>(easymotion-j)
map <Leader><Leader>k <Plug>(easymotion-k)
map <Leader><leader>l <Plug>(easymotion-lineforward)
" 重复上一次操作, 类似repeat插件, 很强大
map <Leader><leader>. <Plug>(easymotion-repeat)

" tagbar setting
nmap <C-o> :TagbarToggle<CR>
nmap <C-j> :TagbarOpen [j] <CR>
let g:tagbar_autofocus = 1
" NERDTREETOGGLE setting
map <C-n> :NERDTreeToggle<CR>

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-surround'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/syntastic'
Plugin 'easymotion/vim-easymotion'
Plugin 'zenorocha/dracula-theme', {'rtp': 'vim/'}
"Plugin 'altercation/solarized',
Plugin 'Shougo/neocomplcache.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

syntax enable
set number

" 配色方案
syntax on
set background=dark
color solarized
"color dracula
